name: flutter_learning_app
description: A learning app with PDF, Video, and Quiz
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  flutter_pdfview: ^1.3.1
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2

flutter:
  assets:
    - assets/
